### ISSUE TITLE
翻译第九章（Variables and scoping）

### ISSUE THREAD

**Issue by luqin** [es6-org/exploring-es6#25]
支持一下。时间: 1周左右。 
原文地址：http://exploringjs.com/es6/ch_variables.html#ch_variables

**Comment by yibuyisheng** [comment]
赞

**Comment by luqin** [comment]
@yibuyisheng 正好读到这部分，并且ES6初学者需要使用`let`和`const`替换`var`。

**Comment by luqin** [comment]
JS 中的 `binding` 翻译成什么好？绑定？

**Comment by yibuyisheng** [comment]
有时候看语境吧？

**Comment by humanPursuit** [comment]
![image](https://cloud.githubusercontent.com/assets/7324767/18502789/e094fd30-7a8b-11e6-903d-0b2a13a8ae83.png)
![image](https://cloud.githubusercontent.com/assets/7324767/18502807/f4765ee8-7a8b-11e6-8ddb-7f57890b71da.png)
第九章第一节这个表格，格式好像不太对吧，`const`和`let`暂存死区拆开了，勘误 @luqin @yibuyisheng

**Comment by yibuyisheng** [comment]
@humanPursuit 多谢指出，已纠正
