### ISSUE TITLE
问一下本书翻译得到原作者授权了吗？

### ISSUE THREAD

**Issue by hax** [es6-org/exploring-es6#28]
如果已经获得授权，应该在README中标明。

**Comment by yibuyisheng** [comment]
贺老，我们尚未联系原作者。谢谢提醒，我会尽快与作者取得联系！^_^

**Comment by yibuyisheng** [comment]
作者的回复让我很忧伤：

> Thanks for the kind words and apologies for the late answer! Alas, I already have a publisher for this book in China. Sorry!

**Comment by hax** [comment]
是不是没问清楚？他给出版商授权了纸质书版权还是连同free online版一起？

另外可问下具体授权的出版社，因为也可能他们并没有找到译者。

**Comment by yibuyisheng** [comment]
好的，多谢指点！我尽快问一下作者吧！

**Comment by yibuyisheng** [comment]
已大致打听到国内出版商了，他们似乎已有翻译人员了。原作者也没有回复我后续的询问邮件，估计此项目要隐藏起来了。

**Comment by luqin** [comment]
国外的技术书籍被盯的很紧啊

**Comment by yibuyisheng** [comment]
这个目前还没有人通知我关掉此项目的，但是我们还是尊重一下原作者吧！

后续我可能还是会坚持自己翻译完这本书，只是不会公开，顶多小范围的线下传阅吧。

**Comment by uooo** [comment]
那我觉得开始翻译其他文章，传播技术更有价值了。

**Comment by yanhaijing** [comment]
支持，顶起来

**Comment by Jocs** [comment]
小范围

**Comment by iugo** [comment]
翻译是一项繁重的工作, 尤其是线上发布的版本, 未来可能存在各种订正.

现在想想, 还是以阅读英文原文加中文心得的方式来学习比较好. 写一堆书评, 在看原文不懂的时候在书评中寻找答案.

**Comment by yibuyisheng** [comment]
@iugo 你说的有一定道理，但仅限于英文阅读能力相对较好的程序员。对于不太会英语的程序员，就 gg 了。

**Comment by iugo** [comment]
@yibuyisheng 总之, 真佩服你的努力. 我把你的译稿小范围分享了.

**Comment by Mr-Wiredancer** [comment]
给你们点赞，看到没能获得授权很可惜... 建议你们把类似 "此项目未经原作者授权" 的信息放在首页 readme 里面

**Comment by hax** [comment]
@yibuyisheng 2年了也没见出版，到底是哪个出版社占了茅坑…… 建议再去沟通下。

**Comment by yibuyisheng** [comment]
@hax 忧伤，没打听到。。

**Comment by chiic** [comment]
一直等呢

**Comment by xland** [comment]
没啥进展
